Test/300 create unit test to package mapping
GreenCityProject/GreenCityMVP21_team1_May pull request #20
Opened 2024-05-20 21:13 UTC by RockTF

Create unit test to GreenCityMVP service/src/main/java/greencity/mapping

 CategoryDtoMapper
 CategoryDtoResponseMapper
 CustomHabitMapper
 CustomShoppingListMapper
 CustomShoppingListResponseDtoMapper
 EcoNewsAuthorDtoMapper
 EcoNewsCommentDtoMapper
 EcoNewsCommentVOMapper
 EcoNewsDtoMapper
 EcoNewsVOMapper
 FilterDtoRequestMapper
 FilterDtoResponseMapper
 HabitAssignDtoMapper
 HabitAssignManagementDtoMapper
 HabitAssignMapper
 HabitAssignUserDurationDtoMapper
 HabitDtoMapper
 HabitFactDtoResponseMapper
 HabitManagementDtoMapper
 HabitStatisticDtoMapper
 HabitStatusCalendarMapper
 HabitStatusCalendarVOMapper
 HabitTranslationDtoMapper
 HabitTranslationMapper
 LanguageTranslationDtoMapper
 MultipartBase64ImageMapper
 NewTagDtoMapper
 SearchNewsDtoMapper
 ShoppingListItemDtoMapper
 ShoppingListItemRequestDtoMapper
 ShoppingListItemResponseDtoMapper
 ShoppingListItemWithStatusRequestDtoMapper
 TagDtoMapper
 TagMapper
 TagVOMapper
 UtilsMapper

2024-05-21 08:19 UTC, nataliiapovzhyk requested changes
comments added across the code

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/CategoryDtoResponseMapperTest.java
> +    CategoryDtoResponseMapper mapper;
should be private

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/EcoNewsCommentDtoMapperTest.java
> +    void convert() {
Display Name annotation is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/HabitTranslationDtoMapperTest.java
> +    HabitTranslation habitTranslation;
private is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/HabitTranslationDtoMapperTest.java
> +    public void testConvert() {
Display Name is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/HabitTranslationMapperTest.java
> +    HabitTranslation habitTranslation;
private is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/HabitTranslationMapperTest.java
> +    public void testConvert() {
display name is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/HabitTranslationMapperTest.java
> +    @Test
Display Name annotation is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/TagDtoMapperTest.java
> +    TagDtoMapper tagDtoMapper = new TagDtoMapper();
private

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/TagDtoMapperTest.java
> +    @Test
Display Name is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/TagMapperTest.java
> +    TagMapper mapper = new TagMapper();
private

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/TagMapperTest.java
> +    void convertTest() {
Display Name is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/TagVOMapperTest.java
> +    TagVOMapper mapper = new TagVOMapper();
private is missing

2024-05-21 08:19 UTC, nataliiapovzhyk commented on service/src/test/java/greencity/mapping/TagVOMapperTest.java
> +    void convertTest() {
Display Name is missing

2024-05-21 08:51 UTC, df7734 reviewed
EcoNewsCommentDtoMapperTest.java failed

Expected :EDITED
Actual   :ORIGINAL 

(Last string)

2024-05-21 12:15 UTC, nataliiapovzhyk commented
> EcoNewsCommentDtoMapperTest.java failed
> 
> Expected :EDITED Actual :ORIGINAL
> 
> (Last string)

updated ModelUnit to make sure that status is EDITED.

2024-05-21 12:25 UTC, nataliiapovzhyk commented
> > EcoNewsCommentDtoMapperTest.java failed
> > Expected :EDITED Actual :ORIGINAL
> > (Last string)
> 
> updated ModelUnit to make sure that status is EDITED.

passes

2024-05-21 12:28 UTC, nataliiapovzhyk approved these changes

2024-05-21 15:29 UTC, df7734 approved these changes

2024-05-22 18:23 UTC, BerserkrMM commented on service/src/test/java/greencity/mapping/CustomShoppingListMapperTest.java
> +                .id(2L)
You can use method from ModelUtils to get CustomShoppingListItemResponseDto.

2024-05-22 18:57 UTC, BerserkrMM commented on service/src/test/java/greencity/mapping/CustomShoppingListResponseDtoMapperTest.java
> +        assertEquals(customShoppingListItem1.getText(), toVerify.get(0).getText());
Item ID has been set but not checked at DTO object.

2024-05-22 19:28 UTC, BerserkrMM commented on service/src/test/java/greencity/mapping/EcoNewsDtoMapperTest.java
> +        assertEquals(ecoNews.getCreationDate(), result.getCreationDate());
ModelUtils.getEcoNews() returned EcoNews with 12 fields. Why you check only 7? (CreationDate,ImagePath,Id,Title,Content,ShortInfo,Author)

Perhaps, if to create expected object, it`ll be more convenient to just compare it with actual result...

2024-05-23 14:56 UTC, BerserkrMM commented on service/src/test/java/greencity/mapping/HabitTranslationDtoMapperTest.java
> +public class HabitTranslationDtoMapperTest {
Public modifiers is not necessary in Tests classes and methods

2024-05-23 16:17 UTC, BerserkrMM approved these changes
All test passes with 100% class coverage

2024-05-24 08:34 UTC, df7734 commented on service/src/test/java/greencity/mapping/HabitTranslationDtoMapperTest.java
> +public class HabitTranslationDtoMapperTest {
Fixed. Thanks for review

2024-05-24 08:35 UTC, merged